.phony: clean all

all:
	make -C linked_list
	make -C linked_list_polimorphic
	make -C function_pointers
	make -C late_binding
	make -C exercise_float_linked_list
	make -C exercise_function_pointers
	make -C exercise_polimorphic_list_of_lists

clean:
	make -C linked_list clean
	make -C linked_list_polimorphic clean
	make -C function_pointers clean
	make -C late_binding clean
	make -C exercise_float_linked_list clean
	make -C exercise_function_pointers clean
	make -C exercise_polimorphic_list_of_lists clean
